### ISSUE TITLE
feature: fork when branching is not possibile

### ISSUE THREAD

**Issue by marco-ippolito** [Eomm/massive-wax#35]
It would be nice to have a flag that allows to fork only if branching from the repository is not possible, rather than manually choosing it in before.

**Comment by Eomm** [comment]
Do you have an idea already how to check if the user has permission to write on the repo?

**Comment by marco-ippolito** [comment]
I think there is a github api for that: 
```
curl -u your_username:your_access_token \
 -H "Accept: application/vnd.github.v3+json" \
 https://api.github.com/repos/octocat/<repo-name>/collaborators/USERNAME/permission
```
this is the [documentation](https://docs.github.com/en/rest/collaborators/collaborators#get-repository-permissions-for-a-user), but this approach would only work on github.
Another solution is to try to push the branch, catch the failure and try to fork it
