### ISSUE TITLE
bug: cannot push on repository with master branch as main

### ISSUE THREAD

**Issue by marco-ippolito** [Eomm/massive-wax#36]
The library doesn't work properly when a repository has its master branch named MAIN.
This error could be easily reproduce by trying to do any change on a repo with main branch.

**Comment by Eomm** [comment]
This `-O` option was introduced to solve it: https://github.com/Eomm/massive-wax/pull/6

Doen't it work as expected?

**Comment by marco-ippolito** [comment]
> This `-O` option was introduced to solve it: #6
> 
> Doen't it work as expected?

It seems it's not working properly, I will add a test case as soon as possible.
